<a href="https://colab.research.google.com/github/timothyllata/fifa-analysis/blob/main/FifaAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The following code must be ran everytime to import the proper libraries.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_squared_error

The following code loads the fifa player CSV file.

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/timothyllata/fifa-analysis/refs/heads/main/fifa_players.csv")
df.head()

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,long_shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing_tackle,sliding_tackle
0,L. Messi,Lionel Andrés Messi Cuccittini,6/24/1987,31,170.18,72.1,"CF,RW,ST",Argentina,94,94,...,94,48,22,94,94,75,96,33,28,26
1,C. Eriksen,Christian Dannemann Eriksen,2/14/1992,27,154.94,76.2,"CAM,RM,CM",Denmark,88,89,...,89,46,56,84,91,67,88,59,57,22
2,P. Pogba,Paul Pogba,3/15/1993,25,190.50,83.9,"CM,CAM",France,88,91,...,82,78,64,82,88,82,87,63,67,67
3,L. Insigne,Lorenzo Insigne,6/4/1991,27,162.56,59.0,"LW,ST",Italy,88,88,...,84,34,26,83,87,61,83,51,24,22
4,K. Koulibaly,Kalidou Koulibaly,6/20/1991,27,187.96,88.9,CB,Senegal,88,91,...,15,87,88,24,49,33,80,91,88,87

The following code replaces all missing values in columns with their corresponding mean. First, this is done for national_rating. In this case, we replace the missing values with 0, because the players do not play for a national team. Then, we replace missing values in all numeric columns with the median. Finally, we replace missing nationa_team and national_team_position values with "None". The sum of na values is than printed to ensure no value are missing.

In [3]:
df["national_rating"] = df["national_rating"].fillna(0)
df = df.fillna(df.median(numeric_only=True))
df['national_team'] = df['national_team'].fillna("None")
df['national_team_position'] = df['national_team_position'].fillna("None")
df.isna().sum()

name                             0
full_name                        0
birth_date                       0
age                              0
height_cm                        0
weight_kgs                       0
positions                        0
nationality                      0
overall_rating                   0
potential                        0
value_euro                       0
wage_euro                        0
preferred_foot                   0
international_reputation(1-5)    0
weak_foot(1-5)                   0
skill_moves(1-5)                 0
body_type                        0
release_clause_euro              0
national_team                    0
national_rating                  0
national_team_position           0
national_jersey_number           0
crossing                         0
finishing                        0
heading_accuracy                 0
short_passing                    0
volleys                          0
dribbling                        0
curve                            0
freekick_accuracy                0
long_passing                     0
ball_control                     0
acceleration                     0
sprint_speed                     0
agility                          0
reactions                        0
balance                          0
shot_power                       0
jumping                          0
stamina                          0
strength                         0
long_shots                       0
aggression                       0
interceptions                    0
positioning                      0
vision                           0
penalties                        0
composure                        0
marking                          0
standing_tackle                  0
sliding_tackle                   0
dtype: int64

This code combines the desired columns from df into chosen_data. Then, a new dataset which contains the club each player plays for combines its club column with with chosen_data to create full_df.

In [4]:
chosen_data = df[list(df.columns[3:7]) + list(df.columns[8:12]) + ["preferred_foot"] + list(df.columns[13:21]) + list(df.columns[22:])].copy()
chosen_data.head()
print(len(chosen_data))

17954

In [5]:
url = "https://raw.githubusercontent.com/timothyllata/fifa-analysis/main/fifa19playerclubs.csv"
club_df = pd.read_csv(url, encoding='latin1')
club_df.head()
print(len(club_df))

18207

In [6]:
chosen_data = chosen_data.reset_index(drop=True)
club_series = club_df["Club"].reset_index(drop=True)

min_len = min(len(chosen_data), len(club_series))

chosen_data = chosen_data.iloc[:min_len]
club_series = club_series.iloc[:min_len]

full_df = pd.concat([chosen_data, club_series], axis=1)
full_df.head()

,age,height_cm,weight_kgs,positions,overall_rating,potential,value_euro,wage_euro,preferred_foot,international_reputation(1-5),...,aggression,interceptions,positioning,vision,penalties,composure,marking,standing_tackle,sliding_tackle,Club
0,31,170.18,72.1,"CF,RW,ST",94,94,110500000.0,565000.0,Left,5,...,48,22,94,94,75,96,33,28,26,FC Barcelona
1,27,154.94,76.2,"CAM,RM,CM",88,89,69500000.0,205000.0,Right,3,...,46,56,84,91,67,88,59,57,22,Juventus
2,25,190.50,83.9,"CM,CAM",88,91,73000000.0,255000.0,Right,4,...,78,64,82,88,82,87,63,67,67,Paris Saint-Germain
3,27,162.56,59.0,"LW,ST",88,88,62000000.0,165000.0,Right,3,...,34,26,83,87,61,83,51,24,22,Manchester United
4,27,187.96,88.9,CB,88,91,60000000.0,135000.0,Right,3,...,87,88,24,49,33,80,91,88,87,Manchester City

Train and Test Split:

The data is split into 70% training data and 30% testing data using the `train_test_split` function from scikit-learn's `model_selection` module.

Model Training:

Now that the dataset is in a format suitable for machine learning, we can train the models. We the Random Forest Regressor from the scikit-learn library to do the training. The predictor variables (age, skill ratings, etc.) are stored in X, and the response variables (overall rating, euro value, etc.) are stored in y.

Model Evaluation:

Each regression model (Overall Rating, Potential, Value, Wage) is assesed with:
- R² Score: Measures how well the model explains the variance in the observed values.
- RMSE (Root Mean Square Error): Quantifies the average magnitude of prediction errors.

In [7]:
def split_data(X, y, test_size=0.3, random_state=42):
    return train_test_split(X, y, test_size=test_size, random_state=random_state)

def train_model(X_train_scaled, y_train):
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X_train_scaled, y_train)
    return model

def evaluate_model(model, X_scaled, y_true, dataset_name="Test"):
    y_pred = model.predict(X_scaled)
    r2 = r2_score(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    print(f"\n{dataset_name} Evaluation:")
    print(f"R²: {r2:.3f}")
    print(f"RMSE: {rmse:.3f}")
    return y_pred, r2, rmse

The model development process is placed into a structured pipeline to ensure consistency and reproducibility.

In [8]:
def run_pipeline(X, y, param_name="Parameter"):
    print(f"\n{'='*60}")
    print(f"Training Model for {param_name}")
    print(f"{'='*60}")
    X_train, X_test, y_train, y_test = split_data(X, y)
    model = train_model(X_train, y_train)
    y_train_pred, r2_train, rmse_train = evaluate_model(model, X_train, y_train, "Train")
    y_test_pred, r2_test, rmse_test = evaluate_model(model, X_test, y_test, "Test")
    results = {
        "Parameter": param_name,
        "R2_Train": r2_train,
        "RMSE_Train": rmse_train,
        "R2_Test": r2_test,
        "RMSE_Test": rmse_test
    }
    return model, pd.DataFrame([results])

The response variables are dropped from X. The categorical columns are then replaced with numerical values to allow the model to interpret them.

In [9]:
X = full_df.drop(columns=['overall_rating', 'potential', 'value_euro', 'wage_euro'])

X = pd.get_dummies(
    X,
    columns=['preferred_foot', 'positions', 'body_type', 'national_team', 'national_team_position', 'Club'],
    drop_first=True
)

y_OR = full_df['overall_rating']  # Train Evaluation: R² 0.996 RMSE 0.445 Test Evaluation: R² 0.972 RMSE 1.184
y_P= full_df['potential']  # Train Evaluation: R² 0.990 RMSE 0.612 Test Evaluation: R² 0.932 RMSE 1.612
# y_VE = full_df['value_euro']  # Train Evaluation: R²: 0.985 RMSE: 671494.902 Test Evaluation: R²: 0.893 RMSE: 1931588.799
y_VE = np.log1p(full_df['value_euro'])  # Train Evaluation: R²: 0.996 RMSE: 0.084 Test Evaluation: R²: 0.974 RMSE: 0.229
y_WE = full_df['wage_euro']  # Train Evaluation: R²: 0.967 RMSE: 3906.885 Test Evaluation: R²: 0.769 RMSE: 10895.698
# y_WE = np.log1p(full_df['wage_euro'])  # Train Evaluation: R²: 0.960 RMSE: 0.243 Test Evaluation: R²: 0.724 RMSE: 0.649

The pipeline is ran for each response variable.

In [10]:
model_OR, results_OR = run_pipeline(X, y_OR, "overall_rating")

============================================================
Training Model for overall_rating
============================================================

Train Evaluation:
R²: 0.996
RMSE: 0.445

Test Evaluation:
R²: 0.971
RMSE: 1.190

In [11]:
model_P, results_P = run_pipeline(X, y_P, "potential")

============================================================
Training Model for potential
============================================================

Train Evaluation:
R²: 0.990
RMSE: 0.613

Test Evaluation:
R²: 0.932
RMSE: 1.612

In [12]:
model_VE, results_VE = run_pipeline(X, y_VE, "value_euro")

============================================================
Training Model for value_euro
============================================================

Train Evaluation:
R²: 0.996
RMSE: 0.084

Test Evaluation:
R²: 0.973
RMSE: 0.230

In [13]:
model_WE, results_WE = run_pipeline(X, y_WE, "wage_euro")

============================================================
Training Model for wage_euro
============================================================

Train Evaluation:
R²: 0.966
RMSE: 3948.531

Test Evaluation:
R²: 0.767
RMSE: 10941.832

In [15]:
results_summary = pd.concat([results_OR, results_P, results_VE, results_WE], ignore_index=True)
results_summary

        Parameter  R2_Train   RMSE_Train   R2_Test     RMSE_Test
0  overall_rating  0.995866     0.446330  0.971186      1.190532
1       potential  0.989900     0.614029  0.932276      1.608344
2      value_euro  0.996360     0.084271  0.973387      0.229913
3       wage_euro  0.966792  3919.281588  0.766070  10957.386774

The following code uses the `feature_importances_` method to display the top 10 explanatory variables for each response variable that was most important in making predictions.

In [1]:
def find_importances(importances):
  importances_df = pd.DataFrame({
      "Feature": skills,
      "Importance": importances
  }).sort_values(by="Importance", ascending=False)
  return importances_df

In [ ]:
skills = X.columns
OR_importances = model_OR.feature_importances_
P_importances = model_P.feature_importances_
VE_importances = model_VE.feature_importances_
WE_importances = model_WE.feature_importances_

In [26]:
OR_importances_df = find_importances(OR_importances)
OR_importances_df.head(10)

                          Feature  Importance
21                      reactions    0.478558
6             release_clause_euro    0.383514
0                             age    0.081586
17                   ball_control    0.008345
35                standing_tackle    0.003588
13                      dribbling    0.002899
3   international_reputation(1-5)    0.002748
33                      composure    0.002472
29                  interceptions    0.002281
34                        marking    0.002127

In [25]:
P_importances_df = find_importances(P_importances)
P_importances_df.head(10)

                Feature  Importance
6   release_clause_euro    0.693686
0                   age    0.184953
21            reactions    0.016669
17         ball_control    0.012734
13            dribbling    0.007456
35      standing_tackle    0.005661
33            composure    0.004501
9             finishing    0.004320
30          positioning    0.003833
29        interceptions    0.003466

In [27]:
VE_importances_df = find_importances(VE_importances)
VE_importances_df.head(10)

                Feature  Importance
6   release_clause_euro    0.921511
17         ball_control    0.025002
21            reactions    0.014188
0                   age    0.006764
35      standing_tackle    0.002784
13            dribbling    0.001942
33            composure    0.001490
9             finishing    0.001423
23           shot_power    0.001325
36       sliding_tackle    0.001269

In [28]:
WE_importances_df = find_importances(WE_importances)
WE_importances_df.head(10)

                          Feature  Importance
6             release_clause_euro    0.643690
3   international_reputation(1-5)    0.062178
21                      reactions    0.032828
17                   ball_control    0.020573
0                             age    0.017520
36                 sliding_tackle    0.012594
33                      composure    0.011500
34                        marking    0.009263
8                        crossing    0.007899
15              freekick_accuracy    0.007293